---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: roboshop
  labels:
    app.kubernetes.io/name: MyApp
spec:
  containers:
  - name: nginx
    image: nginx:stable
    ports:
      - containerPort: 80
        name: http-web-svc


