apiVersion: v1
kind: Pod 
metadata:
  name: multi-containers
spec:
  containers:
    - name: nginx-2
      image: nginx
    - name: sidecar-container
      image: almalinux:8
      command: ["sleep", "200"]