apiVersion: v1
kind: ConfigMap
metadata:
  name: game-demo-pod
data:
  # property-like keys; each key maps to a simple value
  player_initial_lives: "12hsgdi48efeff"
  ui_properties_file_name: "sqlserver"

  # file-like keys
  game.properties: |
    enemy.types=aliens,monsters
    player.maximum-lives=5    
  user-interface.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true    