apiVersion: v1
kind: Pod
metadata:
  name: game-demo-pod
spec:
  containers:
    - name: demo
      image: alpine
      command: ["sleep", "3600"]
      envFrom:
      - configMapRef:
          name: env-variable


        
        