apiVersion: v1
kind: Pod 
metadata: 
  name: serviceloadbalancer
  labels:
    env: dev
  namespace: roboshop
spec:
  containers:
  - name: nginx 
    image: nginx 
    ports:
      - containerPort: 80
        name: http-web
        
---
apiVersion: v1
kind: Service 
metadata: 
  name: nginx-serice 
spec: 
  type: LoadBalancer 
  selector: 
     env: dev
  ports:
  - name: name-of-service
    protocol: TCP
    port: 80
    targetPort: http-web
  
