apiVersion: v1
kind: Pod 
metadata: 
  name: serviceload
  labels:
    env: dev
  namespace: roboshop
spec:
  containers:
  - name: nginx-loadbalancer
    image: nginx 
    ports:
      - containerPort: 80
        
---
apiVersion: v1
kind: Service 
metadata: 
  name: nginx-serice 
spec: 
  type: LoadBalancer 
  ports:
  - port: 80
    targetPort: 80
  selector: 
     env: dev
  
